In [31]:
#pip install tensorflow


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/9e/b8/ed5f794359d05cd0bffb894c6418da87b93016ee17b669d55c45d1bd5d5b/tensorflow-2.13.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.13.0 from https://files.pythonhosted.org/packages/2f/2f/3c84f675931ce3bcbc7e23acbba1e5d7f05ce769adab48322de57a9f5928/tensorflow_intel-2.13.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/126.5 kB ? eta -:--:--
     ------------------ -------------------- 61.4/126.5 kB 1.7 MB/s eta 0:00:01
     ------------------------------------ - 122.9/126.5 kB 2.4 MB/s eta 0:00:01
     -------------------------------------- 126.5/126.5 kB 1.3 MB/s eta 0:00:00
  Obtaining dependency information for flatbuffers>=23.1.21 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
import pandas as pd
import numpy as np
import numpy.random as rnd
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import Perceptron
from sklearn . neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# 1.

In [2]:
df = pd.read_excel('segmentation.xlsx')
display(df)

region_centroid_col  region_centroid_row  region_pixel_count  \
0                     218                  178                   9   
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short_line_density_5  short_line_density_2  vedge_mean  vegde_sd  \
0                     0.11                   0.0        0.83      0.55   
1                     0.00                   0.0        0.28      0.25   
2                     0.00                   0.0        0.94      0.77   
3                     0.00                   0.0        1.72      1.78   
4                     0.00                   0.0        1.44      1.52   
...                    ...                   ...         ...       ...   
2305                  0.00                   0.0        1.22      0.12   
2306                  0.00                   0.0        1.28      0.91   
2307                  0.00                   0.0        1.22      1.00   
2308                  0.00                   0.0        0.56      0.17   
2309                  0.00                   0.0        0.22      0.07   

      hedge_mean  hedge_sd  intensity_mean  rawred_mean  rawblue_mean  \
0           1.11      0.54           59.63        52.44         75.22   
1           0.33      0.37            0.89         0.00          2.56   
2           1.11      1.03          123.04       111.89        139.78   
3           9.00      6.75           43.59        39.56         52.89   
4           2.61      1.93           49.59        44.22         61.56   
...          ...       ...             ...          ...           ...   
2305        1.33      0.80           20.26        20.33         25.00   
2306        0.89      1.14          127.63       117.67        141.67   
2307        1.44      1.17           59.00        51.33         74.44   
2308        0.39      0.33            0.96         0.00          2.78   
2309        0.50      0.08            4.15         3.89          6.67   

      rawgreen_mean  exred_mean  exblue_mean  exgreen_mean  value_mean  \
0             51.22      -21.56        46.78        -25.22       75.22   
1              0.11       -2.67         5.00         -2.33        2.56   
2            117.44      -33.44        50.22        -16.78      139.78   
3             38.33      -12.11        27.89        -15.78       52.89   
4             43.00      -16.11        35.89        -19.78       61.56   
...             ...         ...          ...           ...         ...   
2305          15.44        0.22        14.22        -14.44       25.00   
2306         123.56      -29.89        42.11        -12.22      141.67   
2307          51.22      -23.00        46.33        -23.33       74.44   
2308           0.11       -2.89         5.44         -2.56        2.78   
2309           1.89       -0.78         7.56         -6.78        7.00   

      saturation_mean  hue_mean     classe  
0                0.32     -2.04       path  
1                1.00     -2.12    foliage  
2                0.20     -2.30        sky  
3                0.27     -2.00       path  
4                0.30     -2.02       path  
...               ...       ...        ...  
2305             0.38     -1.56  brickface  
2306             0.17     -2.35        sky  
2307             0.31     -2.09     cement  
2308             1.00     -2.12    foliage  
2309           

# 2.

In [3]:
from sklearn.preprocessing import StandardScaler
dfs = df.iloc[:, :19]
display(dfs)

sca = StandardScaler()
dfS = sca.fit_transform(dfs)
display(dfS)

region_centroid_col  region_centroid_row  region_pixel_count  \
0                     218                  178                   9   
1                     113                  130                   9   
2                     202                   41                   9   
3                      32                  173                   9   
4                      61                  197                   9   
...                   ...                  ...                 ...   
2305                   30                  102                   9   
2306                  143                   24                   9   
2307                   80                   72                   9   
2308                   98                  133                   9   
2309                   19                  147                   9   

      short_line_density_5  short_line_density_2  vedge_mean  vegde_sd  \
0                     0.11                   0.0        0.83      0.55   
1                     0.00                   0.0        0.28      0.25   
2                     0.00                   0.0        0.94      0.77   
3                     0.00                   0.0        1.72      1.78   
4                     0.00                   0.0        1.44      1.52   
...                    ...                   ...         ...       ...   
2305                  0.00                   0.0        1.22      0.12   
2306                  0.00                   0.0        1.28      0.91   
2307                  0.00                   0.0        1.22      1.00   
2308                  0.00                   0.0        0.56      0.17   
2309                  0.00                   0.0        0.22      0.07   

      hedge_mean  hedge_sd  intensity_mean  rawred_mean  rawblue_mean  \
0           1.11      0.54           59.63        52.44         75.22   
1           0.33      0.37            0.89         0.00          2.56   
2           1.11      1.03          123.04       111.89        139.78   
3           9.00      6.75           43.59        39.56         52.89   
4           2.61      1.93           49.59        44.22         61.56   
...          ...       ...             ...          ...           ...   
2305        1.33      0.80           20.26        20.33         25.00   
2306        0.89      1.14          127.63       117.67        141.67   
2307        1.44      1.17           59.00        51.33         74.44   
2308        0.39      0.33            0.96         0.00          2.78   
2309        0.50      0.08            4.15         3.89          6.67   

      rawgreen_mean  exred_mean  exblue_mean  exgreen_mean  value_mean  \
0             51.22      -21.56        46.78        -25.22       75.22   
1              0.11       -2.67         5.00         -2.33        2.56   
2            117.44      -33.44        50.22        -16.78      139.78   
3             38.33      -12.11        27.89        -15.78       52.89   
4             43.00      -16.11        35.89        -19.78       61.56   
...             ...         ...          ...           ...         ...   
2305          15.44        0.22        14.22        -14.44       25.00   
2306         123.56      -29.89        42.11        -12.22      141.67   
2307          51.22      -23.00        46.33        -23.33       74.44   
2308           0.11       -2.89         5.44         -2.56        2.78   
2309           1.89       -0.78         7.56         -6.78        7.00   

      saturation_mean  hue_mean  
0                0.32     -2.04  
1                1.00     -2.12  
2                0.20     -2.30  
3                0.27     -2.00  
4                0.30     -2.02  
...               ...       ...  
2305             0.38     -1.56  
2306             0.17     -2.35  
2307             0.31     -2.09  
2308             1.00     -2.12  
2309             0.71     -1.48  

[2310 rows x 19 columns]

array([[ 1.2761887 ,  0.94973634,  0.        , ...,  0.70102145,
        -0.46877222, -0.43831817],
       [-0.16333606,  0.11453842,  0.        , ..., -0.99219481,
         2.51046151, -0.49010061],
       [ 1.05683255, -1.43405774,  0.        , ...,  2.20548115,
        -0.99451935, -0.6066111 ],
       ...,
       [-0.61575812, -0.89465908,  0.        , ...,  0.68284489,
        -0.51258448, -0.4706822 ],
       [-0.36898245,  0.16673829,  0.        , ..., -0.98706809,
         2.51046151, -0.49010061],
       [-1.45205346,  0.41033768,  0.        , ..., -0.88872825,
         1.23990594, -0.0758411 ]])

In [4]:
dfS = pd.DataFrame(dfS, columns = dfs.columns)
display(dfS)

region_centroid_col  region_centroid_row  region_pixel_count  \
0                1.276189             0.949736                 0.0   
1               -0.163336             0.114538                 0.0   
2                1.056833            -1.434058                 0.0   
3               -1.273827             0.862737                 0.0   
4               -0.876244             1.280336                 0.0   
...                   ...                  ...                 ...   
2305            -1.301246            -0.372660                 0.0   
2306             0.247957            -1.729857                 0.0   
2307            -0.615758            -0.894659                 0.0   
2308            -0.368982             0.166738                 0.0   
2309            -1.452053             0.410338                 0.0   

      short_line_density_5  short_line_density_2  vedge_mean  vegde_sd  \
0                 2.410668             -0.194552   -0.394306 -0.115068   
1                -0.357047             -0.194552   -0.598129 -0.121759   
2                -0.357047             -0.194552   -0.353541 -0.110161   
3                -0.357047             -0.194552   -0.064484 -0.087635   
4                -0.357047             -0.194552   -0.168248 -0.093434   
...                    ...                   ...         ...       ...   
2305             -0.357047             -0.194552   -0.249777 -0.124658   
2306             -0.357047             -0.194552   -0.227542 -0.107039   
2307             -0.357047             -0.194552   -0.249777 -0.105031   
2308             -0.357047             -0.194552   -0.494364 -0.123543   
2309             -0.357047             -0.194552   -0.620364 -0.125773   

      hedge_mean  hedge_sd  intensity_mean  rawred_mean  rawblue_mean  \
0      -0.364251 -0.131018        0.591553     0.560068      0.713087   
1      -0.580366 -0.133910       -0.947427    -0.936970     -0.956566   
2      -0.364251 -0.122685        2.252887     2.257225      2.196611   
3       1.821843 -0.025404        0.171307     0.192374      0.199966   
4       0.051357 -0.107378        0.328506     0.325406      0.399194   
...          ...       ...             ...          ...           ...   
2305   -0.303295 -0.126597       -0.439936    -0.356597     -0.440918   
2306   -0.425206 -0.120814        2.373144     2.422230      2.240041   
2307   -0.272817 -0.120304        0.575047     0.528380      0.695164   
2308   -0.563742 -0.134590       -0.945593    -0.936970     -0.951511   
2309   -0.533264 -0.138842       -0.862016    -0.825920     -0.862123   

      rawgreen_mean  exred_mean  exblue_mean  exgreen_mean  value_mean  \
0          0.469629   -0.765840     1.296593     -1.428854    0.701021   
1         -0.936155    0.865280    -0.838569      0.553118   -0.992195   
2          2.291015   -1.791659     1.472394     -0.698062    2.205481   
3          0.115089    0.050152     0.331222     -0.611475    0.180659   
4          0.243538   -0.295242     0.740061     -0.957822    0.382699   
...             ...         ...          ...           ...         ...   
2305      -0.514502    1.114827    -0.367382     -0.495449   -0.469269   
2306       2.459346   -1.485122     1.057933     -0.303226    2.249524   
2307       0.469629   -0.890182     1.273596     -1.265205    0.682845   
2308      -0.936155    0.846283    -0.816083      0.533203   -0.987068   
2309      -0.887196    1.028478    -0.707741      0.167806   -0.888728   

      saturation_mean  hue_mean  
0           -0.468772 -0.438318  
1            2.510462 -0.490101  
2           -0.994519 -0.606611  
3           -0.687834 -0.412427  
4           -0.556397 -0.425373  
...               ...       ...  
2305        -0.205899 -0.127624  
2306        -1.125956 -0.638975  
2307        -0.512584 -0.470682  
2308         2.510462 -0.490101  
2309         1.239906 -0.075841  

[2310 rows x 19 columns]

# 3.

In [5]:
classe = df['classe'].unique()
print(classe)

['path' 'foliage' 'sky' 'grass' 'brickface' 'cement' 'window']


# 4.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(dfS, df['classe'], test_size=0.3, random_state=42)

# 5.

In [7]:
print("echatilion d'entrainement :", '\n', y_train.value_counts() )
print('\n', "echatilion de test :", '\n', y_test.value_counts() )

echatilion d'entrainement : 
 brickface    244
sky          241
grass        235
path         231
cement       227
window       220
foliage      219
Name: classe, dtype: int64

 echatilion de test : 
 foliage      111
window       110
cement       103
path          99
grass         95
sky           89
brickface     86
Name: classe, dtype: int64


# 6.

In [8]:
per_clf = Perceptron(random_state=42)
per_clf.fit(X_train, y_train) 

Perceptron(random_state=42)

In [9]:
print(X_train.shape)

(1617, 19)


In [10]:
from tensorflow import keras
from tensorflow.keras import layers

# Créer un modèle séquentiel
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(19,)),
    layers.Dense(7, activation='softmax')
])

# Compiler le modèle
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


model.fit(X_train, y_train, epochs=10, batch_size=32)


Epoch 1/10


UnimplementedError: Graph execution error:

Detected at node 'Cast_1' defined at (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
      app.start()
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 711, in start
      self.io_loop.start()
    File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
      self._run_once()
    File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
      handle._run()
    File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
      reply_content = await reply_content
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
      res = shell.run_cell(
    File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3006, in run_cell
      result = self._run_cell(
    File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3061, in _run_cell
      result = runner(coro)
    File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3266, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3445, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Alexis\AppData\Local\Temp\ipykernel_6804\1006896255.py", line 14, in <module>
      model.fit(X_train, y_train, epochs=10, batch_size=32)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1742, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1338, in train_function
      return step_function(self, iterator)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1322, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1303, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1085, in train_step
      return self.compute_metrics(x, y, y_pred, sample_weight)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py", line 1179, in compute_metrics
      self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\compile_utils.py", line 605, in update_state
      metric_obj.update_state(y_t, y_p, sample_weight=mask)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\metrics_utils.py", line 77, in decorated
      update_op = update_state_fn(*args, **kwargs)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\metrics\base_metric.py", line 140, in update_state_fn
      return ag_update_state(*args, **kwargs)
    File "C:\Users\Alexis\AppData\Roaming\Python\Python311\site-packages\keras\src\metrics\base_metric.py", line 708, in update_state
      y_true = tf.cast(y_true, self._dtype)
Node: 'Cast_1'
Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_764]

# 7.

In [11]:
from sklearn.metrics import classification_report


y_pred = per_clf.predict(X_test)


confusion = confusion_matrix(y_test, y_pred)
print("Matrice de confusion :\n", confusion)


report = classification_report(y_test, y_pred)
print("Rapport de classification :\n", report)

Matrice de confusion :
 [[ 84   1   1   0   0   0   0]
 [ 20  65   2   1   5   3   7]
 [  0   0 106   0   0   0   5]
 [  0   0   0  94   1   0   0]
 [  0   0   0   0  99   0   0]
 [  0   0   0   0   0  89   0]
 [  5   4  42   0   1   0  58]]
Rapport de classification :
               precision    recall  f1-score   support

   brickface       0.77      0.98      0.86        86
      cement       0.93      0.63      0.75       103
     foliage       0.70      0.95      0.81       111
       grass       0.99      0.99      0.99        95
        path       0.93      1.00      0.97        99
         sky       0.97      1.00      0.98        89
      window       0.83      0.53      0.64       110

    accuracy                           0.86       693
   macro avg       0.87      0.87      0.86       693
weighted avg       0.87      0.86      0.85       693



# 8.

In [12]:

mlp_tanh = MLPClassifier(hidden_layer_sizes=(30, 30), activation='tanh', max_iter=1000, random_state=1)
mlp_tanh.fit(X_train, y_train)


mlp_sigmoid = MLPClassifier(hidden_layer_sizes=(30, 30), activation='logistic', max_iter=1000, random_state=1)
mlp_sigmoid.fit(X_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(30, 30), max_iter=1000,
              random_state=1)

# 9.

In [13]:
mlp_relu = MLPClassifier(hidden_layer_sizes=(30, 30), activation='relu', max_iter=1000, random_state=1)
mlp_relu.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(30, 30), max_iter=1000, random_state=1)

# 10.

In [14]:
y_pred_relu = mlp_relu.predict(X_test)
confusion_relu = confusion_matrix(y_test, y_pred_relu)
report_relu = classification_report(y_test, y_pred_relu)

# Pour le modèle tanh
y_pred_tanh = mlp_tanh.predict(X_test)
confusion_tanh = confusion_matrix(y_test, y_pred_tanh)
report_tanh = classification_report(y_test, y_pred_tanh)

# Pour le modèle sigmoid
y_pred_sigmoid = mlp_sigmoid.predict(X_test)
confusion_sigmoid = confusion_matrix(y_test, y_pred_sigmoid)
report_sigmoid = classification_report(y_test, y_pred_sigmoid)

In [15]:
print(confusion_sigmoid)
print(report_sigmoid)

[[ 86   0   0   0   0   0   0]
 [  0  96   1   0   0   0   6]
 [  0   3 103   1   0   0   4]
 [  0   0   0  94   1   0   0]
 [  0   0   0   0  99   0   0]
 [  0   0   0   0   0  89   0]
 [  0   1  12   0   0   0  97]]
              precision    recall  f1-score   support

   brickface       1.00      1.00      1.00        86
      cement       0.96      0.93      0.95       103
     foliage       0.89      0.93      0.91       111
       grass       0.99      0.99      0.99        95
        path       0.99      1.00      0.99        99
         sky       1.00      1.00      1.00        89
      window       0.91      0.88      0.89       110

    accuracy                           0.96       693
   macro avg       0.96      0.96      0.96       693
weighted avg       0.96      0.96      0.96       693

